export const allTextStyles = [
    "ASCII",
    "BOLD",
    "ITALIC",
    "BOLD ITALIC",
    "SANS-SERIF",
    "SANS-SERIF BOLD",
    "SANS-SERIF ITALIC",
    "SANS-SERIF BOLD ITALIC",
    "MONOSPACE",
    "SCRIPT",
    "BOLD SCRIPT",
    "FRAKTUR" ,
    "BOLD FRAKTUR",
    "DOUBLE-STRUCK",
    "STRUCK-THROUGH",
    "BOLD STRUCK-THROUGH",
    "ITALIC STRUCK-THROUGH",
    "BOLD ITALIC STRUCK-THROUGH",
    "SANS-SERIF STRUCK-THROUGH",
    "SANS-SERIF BOLD STRUCK-THROUGH",
    "SANS-SERIF ITALIC STRUCK-THROUGH",
    "SANS-SERIF BOLD ITALIC STRUCK-THROUGH",
    "MONOSPACE STRUCK-THROUGH",
    "SCRIPT STRUCK-THROUGH",
    "BOLD SCRIPT STRUCK-THROUGH",
    "FRAKTUR STRUCK-THROUGH",
    "BOLD FRAKTUR STRUCK-THROUGH",
    "DOUBLE-STRUCK STRUCK-THROUGH",
    "UNDERLINED",
    "BOLD UNDERLINED",
    "ITALIC UNDERLINED",
    "BOLD ITALIC UNDERLINED",
    "SANS-SERIF UNDERLINED",
    "SANS-SERIF BOLD UNDERLINED",
    "SANS-SERIF ITALIC UNDERLINED",
    "SANS-SERIF BOLD ITALIC UNDERLINED",
    "MONOSPACE UNDERLINED",
    "SCRIPT UNDERLINED",
    "BOLD SCRIPT UNDERLINED",
    "FRAKTUR UNDERLINED",
    "BOLD FRAKTUR UNDERLINED",
    "DOUBLE-STRUCK UNDERLINED",
    "STRUCK-THROUGH UNDERLINED",
    "BOLD STRUCK-THROUGH UNDERLINED",
    "ITALIC STRUCK-THROUGH UNDERLINED",
    "BOLD ITALIC STRUCK-THROUGH UNDERLINED",
    "SANS-SERIF STRUCK-THROUGH UNDERLINED",
    "SANS-SERIF BOLD STRUCK-THROUGH UNDERLINED",
    "SANS-SERIF ITALIC STRUCK-THROUGH UNDERLINED",
    "SANS-SERIF BOLD ITALIC STRUCK-THROUGH UNDERLINED",
    "MONOSPACE STRUCK-THROUGH UNDERLINED",
    "SCRIPT STRUCK-THROUGH UNDERLINED",
    "BOLD SCRIPT STRUCK-THROUGH UNDERLINED",
    "FRAKTUR STRUCK-THROUGH UNDERLINED",
    "BOLD FRAKTUR STRUCK-THROUGH UNDERLINED",
    "DOUBLE-STRUCK STRUCK-THROUGH UNDERLINED",
] as const;

export type TextStyle = typeof allTextStyles[number];

export const alphabets:Record<TextStyle, string[]> = {
    "ASCII": Array.from("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"),
    "BOLD": Array.from("𝐀𝐁𝐂𝐃𝐄𝐅𝐆𝐇𝐈𝐉𝐊𝐋𝐌𝐍𝐎𝐏𝐐𝐑𝐒𝐓𝐔𝐕𝐖𝐗𝐘𝐙𝐚𝐛𝐜𝐝𝐞𝐟𝐠𝐡𝐢𝐣𝐤𝐥𝐦𝐧𝐨𝐩𝐪𝐫𝐬𝐭𝐮𝐯𝐰𝐱𝐲𝐳𝟎𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗"),
    "ITALIC": Array.from("𝐴𝐵𝐶𝐷𝐸𝐹𝐺𝐻𝐼𝐽𝐾𝐿𝑀𝑁𝑂𝑃𝑄𝑅𝑆𝑇𝑈𝑉𝑊𝑋𝑌𝑍𝑎𝑏𝑐𝑑𝑒𝑓𝑔ℎ𝑖𝑗𝑘𝑙𝑚𝑛𝑜𝑝𝑞𝑟𝑠𝑡𝑢𝑣𝑤𝑥𝑦𝑧𝟢𝟣𝟤𝟥𝟦𝟧𝟨𝟩𝟪𝟫"),
    "BOLD ITALIC": Array.from("𝑨𝑩𝑪𝑫𝑬𝑭𝑮𝑯𝑰𝑱𝑲𝑳𝑴𝑵𝑶𝑷𝑸𝑹𝑺𝑻𝑼𝑽𝑾𝑿𝒀𝒁𝒂𝒃𝒄𝒅𝒆𝒇𝒈𝒉𝒊𝒋𝒌𝒍𝒎𝒏𝒐𝒑𝒒𝒓𝒔𝒕𝒖𝒗𝒘𝒙𝒚𝒛𝟎𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗"),
    "SANS-SERIF": Array.from("𝖠𝖡𝖢𝖣𝖤𝖥𝖦𝖧𝖨𝖩𝖪𝖫𝖬𝖭𝖮𝖯𝖰𝖱𝖲𝖳𝖴𝖵𝖶𝖷𝖸𝖹𝖺𝖻𝖼𝖽𝖾𝖿𝗀𝗁𝗂𝗃𝗄𝗅𝗆𝗇𝗈𝗉𝗊𝗋𝗌𝗍𝗎𝗏𝗐𝗑𝗒𝗓𝟢𝟣𝟤𝟥𝟦𝟧𝟨𝟩𝟪𝟫"),
    "SANS-SERIF BOLD": Array.from("𝗔𝗕𝗖𝗗𝗘𝗙𝗚𝗛𝗜𝗝𝗞𝗟𝗠𝗡𝗢𝗣𝗤𝗥𝗦𝗧𝗨𝗩𝗪𝗫𝗬𝗭𝗮𝗯𝗰𝗱𝗲𝗳𝗴𝗵𝗶𝗷𝗸𝗹𝗺𝗻𝗼𝗽𝗾𝗿𝘀𝘁𝘂𝘃𝘄𝘅𝘆𝘇𝟬𝟭𝟮𝟯𝟰𝟱𝟲𝟳𝟴𝟵"),
    "SANS-SERIF ITALIC": Array.from("𝘈𝘉𝘊𝘋𝘌𝘍𝘎𝘏𝘐𝘑𝘒𝘓𝘔𝘕𝘖𝘗𝘘𝘙𝘚𝘛𝘜𝘝𝘞𝘟𝘠𝘡𝘢𝘣𝘤𝘥𝘦𝘧𝘨𝘩𝘪𝘫𝘬𝘭𝘮𝘯𝘰𝘱𝘲𝘳𝘴𝘵𝘶𝘷𝘸𝘹𝘺𝘻𝟢𝟣𝟤𝟥𝟦𝟧𝟨𝟩𝟪𝟫"),
    "SANS-SERIF BOLD ITALIC": Array.from("𝘼𝘽𝘾𝘿𝙀𝙁𝙂𝙃𝙄𝙅𝙆𝙇𝙈𝙉𝙊𝙋𝙌𝙍𝙎𝙏𝙐𝙑𝙒𝙓𝙔𝙕𝙖𝙗𝙘𝙙𝙚𝙛𝙜𝙝𝙞𝙟𝙠𝙡𝙢𝙣𝙤𝙥𝙦𝙧𝙨𝙩𝙪𝙫𝙬𝙭𝙮𝙯𝟬𝟭𝟮𝟯𝟰𝟱𝟲𝟳𝟴𝟵"),
    "MONOSPACE": Array.from("𝙰𝙱𝙲𝙳𝙴𝙵𝙶𝙷𝙸𝙹𝙺𝙻𝙼𝙽𝙾𝙿𝚀𝚁𝚂𝚃𝚄𝚅𝚆𝚇𝚈𝚉𝚊𝚋𝚌𝚍𝚎𝚏𝚐𝚑𝚒𝚓𝚔𝚕𝚖𝚗𝚘𝚙𝚚𝚛𝚜𝚝𝚞𝚟𝚠𝚡𝚢𝚣𝟶𝟷𝟸𝟹𝟺𝟻𝟼𝟽𝟾𝟿"),
    "SCRIPT": Array.from("𝒜ℬ𝒞𝒟ℰℱ𝒢ℋℐ𝒥𝒦ℒℳ𝒩𝒪𝒫𝒬ℛ𝒮𝒯𝒰𝒱𝒲𝒳𝒴𝒵𝒶𝒷𝒸𝒹ℯ𝒻ℊ𝒽𝒾𝒿𝓀𝓁𝓂𝓃ℴ𝓅𝓆𝓇𝓈𝓉𝓊𝓋𝓌𝓍𝓎𝓏𝟢𝟣𝟤𝟥𝟦𝟧𝟨𝟩𝟪𝟫"),
    "BOLD SCRIPT": Array.from("𝓐𝓑𝓒𝓓𝓔𝓕𝓖𝓗𝓘𝓙𝓚𝓛𝓜𝓝𝓞𝓟𝓠𝓡𝓢𝓣𝓤𝓥𝓦𝓧𝓨𝓩𝓪𝓫𝓬𝓭𝓮𝓯𝓰𝓱𝓲𝓳𝓴𝓵𝓶𝓷𝓸𝓹𝓺𝓻𝓼𝓽𝓾𝓿𝔀𝔁𝔂𝔃𝟎𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗"),
    "FRAKTUR": Array.from("𝔄𝔅ℭ𝔇𝔈𝔉𝔊ℌℑ𝔍𝔎𝔏𝔐𝔑𝔒𝔓𝔔ℜ𝔖𝔗𝔘𝔙𝔚𝔛𝔜ℨ𝔞𝔟𝔠𝔡𝔢𝔣𝔤𝔥𝔦𝔧𝔨𝔩𝔪𝔫𝔬𝔭𝔮𝔯𝔰𝔱𝔲𝔳𝔴𝔵𝔶𝔷𝟘𝟙𝟚𝟛𝟜𝟝𝟞𝟟𝟠𝟡"),
    "BOLD FRAKTUR": Array.from("𝕬𝕭𝕮𝕯𝕰𝕱𝕲𝕳𝕴𝕵𝕶𝕷𝕸𝕹𝕺𝕻𝕼𝕽𝕾𝕿𝖀𝖁𝖂𝖃𝖄𝖅𝖆𝖇𝖈𝖉𝖊𝖋𝖌𝖍𝖎𝖏𝖐𝖑𝖒𝖓𝖔𝖕𝖖𝖗𝖘𝖙𝖚𝖛𝖜𝖝𝖞𝖟𝟎𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗"),
    "DOUBLE-STRUCK": Array.from("𝔸𝔹ℂ𝔻𝔼𝔽𝔾ℍ𝕀𝕁𝕂𝕃𝕄ℕ𝕆ℙℚℝ𝕊𝕋𝕌𝕍𝕎𝕏𝕐ℤ𝕒𝕓𝕔𝕕𝕖𝕗𝕘𝕙𝕚𝕛𝕜𝕝𝕞𝕟𝕠𝕡𝕢𝕣𝕤𝕥𝕦𝕧𝕨𝕩𝕪𝕫𝟘𝟙𝟚𝟛𝟜𝟝𝟞𝟟𝟠𝟡"),
    "STRUCK-THROUGH": [],
    "BOLD STRUCK-THROUGH": [],
    "ITALIC STRUCK-THROUGH": [],
    "BOLD ITALIC STRUCK-THROUGH": [],
    "SANS-SERIF STRUCK-THROUGH": [],
    "SANS-SERIF BOLD STRUCK-THROUGH": [],
    "SANS-SERIF ITALIC STRUCK-THROUGH": [],
    "SANS-SERIF BOLD ITALIC STRUCK-THROUGH": [],
    "MONOSPACE STRUCK-THROUGH": [],
    "SCRIPT STRUCK-THROUGH": [],
    "BOLD SCRIPT STRUCK-THROUGH": [],
    "FRAKTUR STRUCK-THROUGH": [],
    "BOLD FRAKTUR STRUCK-THROUGH": [],
    "DOUBLE-STRUCK STRUCK-THROUGH": [],
    "UNDERLINED": [],
    "BOLD UNDERLINED": [],
    "ITALIC UNDERLINED": [],
    "BOLD ITALIC UNDERLINED": [],
    "SANS-SERIF UNDERLINED": [],
    "SANS-SERIF BOLD UNDERLINED": [],
    "SANS-SERIF ITALIC UNDERLINED": [],
    "SANS-SERIF BOLD ITALIC UNDERLINED": [],
    "MONOSPACE UNDERLINED": [],
    "SCRIPT UNDERLINED": [],
    "BOLD SCRIPT UNDERLINED": [],
    "FRAKTUR UNDERLINED": [],
    "BOLD FRAKTUR UNDERLINED": [],
    "DOUBLE-STRUCK UNDERLINED": [],
    "STRUCK-THROUGH UNDERLINED": [],
    "BOLD STRUCK-THROUGH UNDERLINED": [],
    "ITALIC STRUCK-THROUGH UNDERLINED": [],
    "BOLD ITALIC STRUCK-THROUGH UNDERLINED": [],
    "SANS-SERIF STRUCK-THROUGH UNDERLINED": [],
    "SANS-SERIF BOLD STRUCK-THROUGH UNDERLINED": [],
    "SANS-SERIF ITALIC STRUCK-THROUGH UNDERLINED": [],
    "SANS-SERIF BOLD ITALIC STRUCK-THROUGH UNDERLINED": [],
    "MONOSPACE STRUCK-THROUGH UNDERLINED": [],
    "SCRIPT STRUCK-THROUGH UNDERLINED": [],
    "BOLD SCRIPT STRUCK-THROUGH UNDERLINED": [],
    "FRAKTUR STRUCK-THROUGH UNDERLINED": [],
    "BOLD FRAKTUR STRUCK-THROUGH UNDERLINED": [],
    "DOUBLE-STRUCK STRUCK-THROUGH UNDERLINED": [],
}

const decorate = (alphabet: string[], char: string) => alphabet.map(ch => `${ch}${char}`);

Object.keys(alphabets).filter(style => !/STRUCK-THROUGH/.test(style)).forEach(style => {
    const decoratedStyle = style === "ASCII" ? "STRUCK-THROUGH" : `${style} STRUCK-THROUGH` as TextStyle;
    alphabets[decoratedStyle] = decorate(alphabets[style as TextStyle],  "\u0336");
})

Object.keys(alphabets).filter(style => !/UNDERLINED/.test(style)).forEach(style => {
    const decoratedStyle = style === "ASCII" ? "UNDERLINED" : `${style} UNDERLINED` as TextStyle;
    alphabets[decoratedStyle] = decorate(alphabets[style as TextStyle],  "\u0332");
})
